#!/bin/sh
#
# Init file for TPM 1.2 bios for simulator 
#
# chkconfig:   <default runlevel(s)> <start> <stop>
# description: TPM 1.2 bios daemon

# processname: tpm12-tpmbios
# config: /etc/default/tpm12-simulator

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/local/bin/tpmbios"
prog="tpm12-tpmbios"
config="/etc/default/tpm12-simulator"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

[ -e $config ] && . $config

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    # if not running, start it up here, usually something like "daemon $exec"
    daemon --user=tss $exec
    retval=$?
    echo
    [ $retval -eq 0 ] 
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    # stop it here, often "killproc $prog"
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
exit $?
